### ISSUE TITLE
Bug after latest update: cannot start

### ISSUE THREAD

**Issue by schklom** [LibreTranslate/LibreTranslate#375]
On a `linux/amd64` machine
docker-compose.yaml:
```yaml
services:
  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    hostname: libretranslate
    environment:
      # https://github.com/LibreTranslate/LibreTranslate#arguments
      # https://github.com/LibreTranslate/LibreTranslate#manage-api-keys
      LT_HOST: 0.0.0.0 # 127.0.0.1
      LT_PORT: 5000
      LT_FRONTEND_LANGUAGE_SOURCE: "en"
      LT_FRONTEND_LANGUAGE_TARGET: en
      # LT_FRONTEND_TIMEOUT: 500
      LT_API_KEYS: "true"
      LT_API_KEYS_DB_PATH: /libretranslate_db.db
      LT_THREADS: 2 # 4
      LT_REQUIRE_API_KEY_ORIGIN: "true"
      LT_REQ_LIMIT: 20 # no limit
      LT_BATCH_LIMIT: 2 # no limit
    volumes:
      - ${DOCKER}/libretranslate_db/libretranslate_db.db:/libretranslate_db.db
      - ${DOCKER}/libretranslate/.local:/home/libretranslate/.local
    ports:
      5000:5000
```

Logs:
```sh
$ docker logs libretranslate
(URLError(TimeoutError(110, 'Connection timed out')),)
(URLError(TimeoutError(110, 'Connection timed out')),)
(URLError(TimeoutError(110, 'Connection timed out')),)
(URLError(TimeoutError(110, 'Connection timed out')),)
Updating language models
Found 58 models
Downloading Arabic → English (1.0) ...
Downloading Azerbaijani → English (1.5) ...
Downloading Catalan → English (1.7) ...
Downloading Chinese → English (1.7) ...
Downloading Czech → English (1.5) ...
Downloading Danish → English (1.3) ...
Downloading Dutch → English (1.4) ...
Downloading English → Arabic (1.0) ...
Downloading English → Azerbaijani (1.5) ...
Downloading English → Catalan (1.7) ...
Downloading English → Chinese (1.7) ...
Downloading English → Czech (1.5) ...
Downloading English → Danish (1.3) ...
Downloading English → Dutch (1.4) ...
Downloading English → Esperanto (1.5) ...
Downloading English → Finnish (1.5) ...
Downloading English → French (1.0) ...
Downloading English → German (1.0) ...
Downloading English → Greek (1.5) ...
Downloading English → Hebrew (1.5) ...
Downloading English → Hindi (1.1) ...
Downloading English → Hungarian (1.5) ...
Downloading English → Indonesian (1.2) ...
Downloading English → Irish (1.1) ...
Downloading English → Italian (1.0) ...
Downloading English → Japanese (1.1) ...
Downloading English → Korean (1.1) ...
Downloading English → Persian (1.5) ...
Downloading English → Polish (1.1) ...
Downloading English → Portuguese (1.0) ...
Downloading English → Russian (1.7) ...
Downloading English → Slovak (1.5) ...
Downloading English → Spanish (1.0) ...
Downloading English → Swedish (1.5) ...
Downloading English → Turkish (1.5) ...
Downloading English → Ukranian (1.4) ...
Downloading Esperanto → English (1.5) ...
Downloading Finnish → English (1.5) ...
Downloading French → English (1.0) ...
Downloading German → English (1.0) ...
Downloading Greek → English (1.5) ...
Downloading Hebrew → English (1.5) ...
Downloading Hindi → English (1.1) ...
Downloading Hungarian → English (1.5) ...
Downloading Indonesian → English (1.2) ...
Downloading Irish → English (1.1) ...
Downloading Italian → English (1.0) ...
Downloading Japanese → English (1.1) ...
Downloading Korean → English (1.1) ...
Downloading Persian → English (1.5) ...
Downloading Polish → English (1.1) ...
Downloading Portuguese → English (1.0) ...
Downloading Russian → English (1.0) ...
Downloading Slovak → English (1.5) ...
Downloading Spanish → English (1.0) ...
Downloading Swedish → English (1.5) ...
Downloading Turkish → English (1.5) ...
Downloading Ukranian → English (1.4) ...
Cannot update models (normal if you're offline): name 'app' is not defined
Traceback (most recent call last):
  File "./venv/bin/libretranslate", line 33, in <module>
    sys.exit(load_entry_point('libretranslate==1.3.8', 'console_scripts', 'libretranslate')())
  File "/app/venv/lib/python3.8/site-packages/libretranslate/main.py", line 176, in main
    app = create_app(args)
  File "/app/venv/lib/python3.8/site-packages/libretranslate/app.py", line 163, in create_app
    limiter = Limiter(
  File "/app/venv/lib/python3.8/site-packages/flask_limiter/extension.py", line 272, in __init__
    self.init_app(app)
  File "/app/venv/lib/python3.8/site-packages/flask_limiter/extension.py", line 278, in init_app
    config = app.config
AttributeError: 'Blueprint' object has no attribute 'config'
```

**Comment by pierotofy** [comment]
Thanks for the report @schklom :pray: this was mistakely introduced with https://github.com/LibreTranslate/LibreTranslate/commit/638d664cffdb325cfc32fc3d7333da2455c56e2f but should be fixed with https://github.com/LibreTranslate/LibreTranslate/commit/e74cdd4db305c46825c2cb0f9225e3bd8d1d68f9

**Comment by schklom** [comment]
Damn that was quick, thank you for the fix! :)
